version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "2137:5432"
  rust:
    build: .
    image: pms_backend
    restart: always
    volumes:
      - .:/app
    working_dir: /app
  
      