max_width = 100
imports_granularity = "Crate"
imports_layout = "Mixed"
reorder_imports = true
group_imports = "StdExternalCrate"
wrap_comments = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
comment_width = 100
format_code_in_doc_comments = true
